env: "local" # local, dev, prod
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "postgres1"
  sslmode: "disable"
http_server:
  address: "localhost:8080"
  timeout: 10s
  idle_timeout: 30s
